name: unit-test-script

on: [push]

jobs:
  run-tests: 
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "pypy3.9", "pypy3.10"]
    steps:
      - uses: actions/checkout@v4
      - run: echo "job running on ${{ runner.os }}"
      - run: python -V
      - if: ${{ runner.os == "Windows" }}
        run: echo "Running on Windows"
      - if: ${{ runner.os }} != Windows
        run: echo "running on Non Windows"
